apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-config
  namespace: emqx
data:
  EMQX_CLUSTER__STATIC__SEEDS: "emqx@emqx-0.emqx-headless.emqx.svc.cluster.local,emqx@emqx-1.emqx-headless.emqx.svc.cluster.local,emqx@emqx-2.emqx-headless.emqx.svc.cluster.local"
